package com.guoshou.spark.po.NB

case class Branch(branchNo: String,
        cityCode: String,
        branchName: String,
        prioBranchNo: String,
        branchPostCode: String,
        branchTel: String,
        branchAddress: String,
        branchFax: String,
        branchEmailNo: String,
        branchPolDefflag: Double,
        branchSearchName: String,
        processingCenter: String,
        branchClassNo: String,
        printInfoBranch: String,
        archiveBranch: String,
        printBranchName: String,
        branchGrp: String,
        branchPosition: String,
        businessLic: String,
        taxpayerId: String,
        serviceTel: String,
        webAddr: String)
