package com.guoshou.spark.po.NB

import java.sql.Date

case class MioLog(mioLogId: Double,
                  plnmioRecId: Double,
                  polCode: String,
                  cntrType: String,
                  cgNo: String,
                  sgNo: String,
                  cntrNo: String,
                  mtnId: Double,
                  mtnItemCode: String,
                  ipsnNo: Double,
                  mioCustNo: String,
                  mioCustName: String,
                  plnmioDate: Date,
                  mioDate: Date,
                  mioLogUpdTime: Date,
                  premDeadline: Date,
                  mioItemCode: String,
                  mioTypeCode: String,
                  mgrBranchNo: String,
                  oclkBranchNo: String,
                  oclkClerkNo: String,
                  salesBranchNo: String,
                  salesChannel: String,
                  salesNo: String,
                  mioClass: Double,
                  amnt: Double,
                  bankCode: String,
                  bankAccNo: String,
                  mioTxClass: Double,
                  mioTxNo: Double,
                  corrMioDate: Date,
                  corrMioTxNo: Double,
                  receiptNo: String,
                  voucherNo: String,
                  clearingMioTxNo: String,
                  finPlnmioDate: Date,
                  remark: String,
                  netIncome: Double,
                  vat: Double,
                  vatRate: Double,
                  vatId: String,
                  branchTypeFlag: String,
                  finAccNo: String,
                  finChannel: String,
                  chargeNo: String,
                  systemId: String,
                  topayLogId: String)




case class StatisticsB3(
                               years: Double,
                               times: Double,
                               polFrom: String,
                               polCode: String,
                               polName: String,
                               dateFrom: String,
                               payRCnt: Double,
                               payRAmt: Double,
                               payXCnt: Double,
                               payXAmt: Double,
                               surXAmt: Double,
                               mrType: String,
                               procDate: String
                             )

case class StatisticsB4(
                               years: BigDecimal,
                               times: BigDecimal,
                               busSys: String,
                               proBranchNo: String,
                               regBranchNo: String,
                               applBranchNo: String,
                               cntrNo: String,
                               polCode: String,
                               inForceDate: String,
                               amendDate: String,
                               faceAmnt: BigDecimal,
                               amendType: String,
                               remark: String
                             )

case class SvrGroup(
                           sgId: Double,
                           custNo: String,
                           contactSeq: Double,
                           applNo: String,
                           sgNo: String,
                           sgType: String,
                           mgrBranchNo: String,
                           sgCntrNum: Double,
                           salesChannel: String,
                           salesBranchNo: String,
                           salesCode: String,
                           moneyinItrvl: String,
                           moneyinDate: Date,
                           moneyinType: String,
                           sumPrem: Double,
                           applDate: Date,
                           evDate: Date,
                           billLastPrtDate: Date,
                           inForceDate: Date,
                           autoInForceDate: Date,
                           signDate: Date,
                           bankCode: String,
                           bankAccNo: String,
                           accCustName: String,
                           cntrExpiryDate: Date,
                           loseRegNum: Double,
                           cntrTermCause: String,
                           cntrTermDate: Date,
                           cntrStat: String,
                           masterSgId: Double,
                           mrType: String,
                           polCode: String,
                           renewTimes: Double,
                           originalCntrNo: String
                         )

case class SvrGroupLst(
                              sgId: Double,
                              cntrNo: String,
                              ipsnCategory: Double,
                              ipsnNo: Double
                            )

case class BizParameter(
                                 bizParamCode: String,
                                 bizParamVal: String,
                                 bizParamChn: String
                               )


case class MtnOsmbShift(
                               mtnId: Double,
                               shiftType: String,
                               cntrNo: String,
                               outBranchNo: String,
                               outBranchChn: String,
                               outAddr: String,
                               outPostcode: String,
                               outOaAddr: String,
                               outTele: String,
                               outConnector: String,
                               outReason: String,
                               applName: String,
                               applSex: String,
                               applIdNo: String,
                               applAddr: String,
                               applPostcode: String,
                               applTel: String,
                               phrAddr: String,
                               phrPostcode: String,
                               phrTel: String,
                               osmbReserve: Double,
                               osmbFee: Double,
                               inBranchNo: String,
                               inBranchChn: String,
                               inAddr: String,
                               inPostcode: String,
                               inOaAddr: String,
                               inTel: String,
                               inConnector: String,
                               cgCount: Double,
                               isNew: String,
                               idType: String,
                               newHometel: String,
                               newOfficetel: String,
                               newEmail: String,
                               centerCode: String
                             )

case class PlnmioRec(
                            plnmioRecId: Double,
                            cntrType: String,
                            sgNo: String,
                            cgNo: String,
                            archiveBranch: String,
                            signYear: Double,
                            polCode: String,
                            cntrNo: String,
                            mtnId: Double,
                            mtnItemCode: String,
                            ipsnNo: Double,
                            mioCustNo: String,
                            mioCustName: String,
                            mioClass: Double,
                            plnmioDate: Date,
                            premDeadline: Date,
                            mioItemCode: String,
                            mioTypeCode: String,
                            mgrBranchNo: String,
                            salesChannel: String,
                            salesBranchNo: String,
                            salesNo: String,
                            amnt: Double,
                            lockFlag: String,
                            bankCode: String,
                            bankAccNo: String,
                            holdFlag: String,
                            voucherNo: String,
                            finPlnmioDate: Date,
                            clearingMioTxNo: String,
                            mioProcFlag: String,
                            accId: Double,
                            remark: String,
                            plnmioCreateTime: Date,
                            mtnNo: String,
                            sysNoOriginal: String,
                            systemId: String,
                            topayLogId: String
                          )

case class SgAppl(
                         applId: Double,
                         applNo: String,
                         unevCustId: Double,
                         contactSeq: Double,
                         applType: String,
                         inForceStFlag: String,
                         prtInvoiceType: String,
                         sgNo: String,
                         sgType: String,
                         sgCntrNum: Double,
                         moneyinItrvl: String,
                         polCode: String,
                         moneyinDate: Date,
                         moneyinType: String,
                         bankCode: String,
                         bankaccNo: String,
                         bankaccName: String,
                         sumPrem: Double,
                         applDate: Date,
                         evDate: Date,
                         mgrBranchNo: String,
                         acceptBranchNo: String,
                         acceptDeptType: String,
                         acceptDeptNo: Double,
                         bizAcceptDate: Date,
                         sysAcceptDate: Date,
                         salesChannel: String,
                         salesBranchNo: String,
                         salesCode: String,
                         oclkClerkNo: String,
                         oclkBranchNo: String,
                         prtDate: Date,
                         ernstPrem: Double,
                         applEntBranchNo: String,
                         applEntClerkNo: String,
                         listEntBranchNo: String,
                         listEntClerkNo: String,
                         applChkBranchNo: String,
                         applChkClerkNo: String,
                         listChkBranchNo: String,
                         listChkClerkNo: String,
                         recvMode: String,
                         accesschannel: String,
                         amendArcNo: String,
                         oldCntrNo: String,
                         nextMoneyinDate: Date
                       )


case class StdContract(
                               cntrId: Double,
                               cntrFrom: String,
                               applNo: String,
                               cntrType: String,
                               cntrNo: String,
                               loseRegNum: Double,
                               originalCntrNo: String,
                               polCode: String,
                               mrType: String,
                               masterCntrId: Double,
                               cntrStat: String,
                               cntrTermCause: String,
                               cntrTermDate: Date,
                               cgNo: String,
                               sgNo: String,
                               ipsnNum: Double,
                               termIpsnNum: Double,
                               applDate: Date,
                               signDate: Date,
                               inForceDate: Date,
                               autoInForceDate: Date,
                               renewFlag: String,
                               renewTimes: Double,
                               mgrBranchNo: String,
                               salesChannel: String,
                               oSalesBranchNo: String,
                               oSalesCode: String,
                               nSalesBranchNo: String,
                               nSalesCode: String,
                               cntrExpiryDate: Date,
                               moneyinItrvl: String,
                               moneyinItrvlMon: Double,
                               bddType: String,
                               paidupFlag: String,
                               cvForPremFlag: String,
                               moneyinType: String,
                               bankCode: String,
                               bankAccNo: String,
                               accCustName: String,
                               saleCode: String,
                               schemeCode: String,
                               giftType: String,
                               otherInsurFlag: String,
                               currencyCode: String
                             )


//case class EndowAcc(
//                           accId: Double,
//                           mgrBranchNo: String,
//                           accNo: String,
//                           accNoSeq: Double,
//                           custNo: String,
//                           accOpenDate: Date,
//                           maturity: Date,
//                           accCloseDate: Date,
//                           accTypeCode: String,
//                           cashType: String,
//                           accStat: String,
//                           settledIntRate: Double,
//                           lastUpdDate: Date,
//                           balance: Double,
//                           frozenBalance: Double,
//                           intCalBase: Double,
//                           unsettledInt: Double,
//                           lastSettleDate: Date,
//                           lastSettleBalance: Double,
//                           intCalType: String,
//                           settleCycle: String,
//                           settleDay: String,
//                           settleType: String,
//                           accExtractDate:Date,
//                           unsettledDate: Date,
//                           polCode: String,
//                           oriAccTypeCode: String
//                         )


case class EndowAcc(accId: Double,
                    mgrBranchNo: String,
                    accNo: String,
                    accNoSeq: Double,
                    custNo: String,
                    accOpenDate: Date,
                    maturity: Date,
//                    accCloseDate: Date,
                    accCloseDate: String,
                    accTypeCode: String,
                    cashType: String,
                    accStat: String,
                    settledIntRate: Double,
                    lastUpdDate: Date,
                    balance: Double,
                    frozenBalance: Double,
                    intCalBase: Double,
                    unsettledInt: Double,
                    lastSettleDate: Date,
                    lastSettleBalanc: Double,
                    intCalType: String,
                    settleCycle: String,
                    settleDay: String,
                    settleType: String,
//                    accExtractDate: Date,
//                    unsettledDate: Date,
                    accExtractDate: String,
                    unsettledDate: String,
                    polCode: String,
                    oriAccTypeCode: String)
